#+TITLE: Computer Graphics Notes
* General
** What is a isocline (also known as contour line)?
   A contour line (also isocline, isopleth, isarithm, or equipotential curve) of a function of two variables is a curve along which the function has a constant value, so that the curve joins points of equal value. It is a plane section of the three-dimensional graph of the function f(x, y) parallel to the x, y plane. In cartography, a contour line (often just called a "contour") joins points of equal elevation (height) above a given level, such as mean sea level. (Taken from wikipedia)
** What is an isosurface? 
   An isosurface is a three-dimensional analog of an isoline. It is a surface that represents points of a constant value (e.g. pressure, temperature, velocity, density) within a volume of space; in other words, it is a level set of a continuous function whose domain is 3D-space. (Taken from wikipedia)
** In ray-tracing, what kind of geometric objects does the ray-tracer need to have operations against?
- Spheres, boxes, planes, quadrics (cylinders, cones, ellipsoids, paraboloids, hyperboloids, etc.)
- *Note*: The above classification is taken form the book "An Introduction to Ray Tracing" by Andrew S. Glassner. I'm not sure how exhaustive this list is, but I'm writing these down and reading more about some of the the more complicated shapes to help understand more how a ray-tracer works. Specifically, implicit surfaces and isosurfaces. I'm hoping the research I do on these will help me understand some more complicated math topics
** What are the three main models of shading?
   - Flat shading, Gourad shading and Phong shading
** What is flat shading?
   This is the most simple and efficient way to specify color for an object. It defines a single color for a face. Implementations of it may vary, but the main idea is that we use only one surface normal per polygon. The color itself is uniform (unchanging) on that polygon.
** What is Gourad shading?
   This was invented as an improvement to allow for more smooth transitions of the color on round objects. Main idea is that there is a different normal per vertex and the color is calculated in the vertex shader. That color is then interpolated over the polygon. Because there are less vertices then there are fragments, then calculating the color per vertex and interpolating it, is more efficient than calculating it per fragment.

   This approach handles badly materials that have a specular reflection. This reflection might occur inside the polygon, but not on any of the vertices. Thus this shading would not show it, if it does not happen to be on the vertex.
** What is Phong shading?
   This was another improvement in order to account for the specular reflection. Main idea is that the normal from the vertices is interpolated. Color is calculated per fragment, taking into account the interpolated normal. For an approximation of a sphere, this is quite ideal, because the interpolated normals would be exactly those that a perfect sphere would have. Because the color is calculated based on the normals, it will be calculated as if it were a perfect sphere.
